apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: ecommerce
data:
  EMAIL: hzdevops52@gmail.com
  NAME: E-Commerce Test
  REACT_APP_FRONTEND_URL: http://localhost:9090
  MONGO_URI: mongodb://mongodb-service:27017/ecommerce
