apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: ecommerce

spec:
  replicas: 1
    
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment

    spec:
      imagePullSecrets:
        - name: ghcr-secret
        
      containers:
        - name: backend
          image: ghcr.io/hzdevops52/e-backend:test

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-configmap

            - secretRef:
                name: backend-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10