apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend-deployment

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
