apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.mongodb.service.type}}
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.service.port}}
      targetPort: {{ .Values.mongodb.service.targetPort}}
