apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: {{ .Release.Namespace }}

spec:
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}

  volumeMode: {{ .Values.mongodb.persistence.volumeMode }}

  accessModes:
    {{- range .Values.mongodb.persistence.accessModes }}
    - {{ . }}
    {{- end }}